### ISSUE TITLE
Resistor script errors with zero-ohm resistors

### ISSUE THREAD

**Issue by normaldotcom** [normaldotcom/python-digikey#1]
```
C:\repos\python-digikey (master)                                                                               
λ C:\Python27\python.exe resistor 0 --package 1206                                                             
Traceback (most recent call last):                                                                             
  File "resistor", line 31, in <module>                                                                        
    lambda s: digikey.within_tolerance(digikey.parse_number(args.resistance), args.error, digikey.parse_number(
s))))                                                                                                          
  File "C:\repos\python-digikey\digikey\__init__.py", line 77, in produce_filter_options                       
    if func(' '.join(x for x in option if not isinstance(x, BeautifulSoup.Comment)))]                          
  File "resistor", line 31, in <lambda>                                                                        
    lambda s: digikey.within_tolerance(digikey.parse_number(args.resistance), args.error, digikey.parse_number(
s))))                                                                                                          
  File "C:\repos\python-digikey\digikey\__init__.py", line 54, in within_tolerance                             
    return abs(actual - desired)/desired <= tolerance_percent/100                                              
ZeroDivisionError: float division by zero                                                                      
```

**Comment by normaldotcom** [comment]
Workaround added in bb4ace7ec19b0fb197a5d20dc5fd4aab62755b20
